### ISSUE TITLE
sdxl training not working in v1.2.5

### ISSUE THREAD

**Issue by scyomantion** [bghira/SimpleTuner#1317]
Hi,

since Version v1.2.5 its not Possible to train SDXL, I get following error:

```
***** Running training *****
-  Num batches = 18
-  Num Epochs = 556
  - Current Epoch = 1
-  Total train batch size (w. parallel, distributed & accumulation) = 20
  - Instantaneous batch size per device = 20
  - Gradient Accumulation steps = 1
-  Total optimization steps = 10000
-  Total optimization steps remaining = 10000
Epoch 1/556, Steps:   0%|                                                                          | 0/10000 [00:00<?, ?it/s]'tuple' object has no attribute 'flatten'
Traceback (most recent call last):
  File "/finetune/SimpleTuner/train.py", line 71, in <module>
    trainer.train()
  File "/finetune/SimpleTuner/helpers/training/trainer.py", line 2809, in train
    model_pred = self.model_predict(
                 ^^^^^^^^^^^^^^^^^^^
  File "/finetune/SimpleTuner/helpers/training/trainer.py", line 2293, in model_predict
    model_pred = self.unet(
                 ^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/accelerate/utils/operations.py", line 823, in forward
    return model_forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/accelerate/utils/operations.py", line 811, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1152, in forward
    aug_emb = self.get_aug_embed(
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 980, in get_aug_embed
    time_embeds = self.add_time_proj(time_ids.flatten())
                                     ^^^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'flatten'

Epoch 1/556, Steps:   0%|                                                                          | 0/10000 [00:00<?, ?it/s]
```

Thank you very much for your great work

**Comment by KBRASK** [comment]
I solved the problem, and the issue was at line 2364 in ./helpers/training/trainer.py:

```python
if time_ids is not None and hasattr(time_ids, "to"):
    batch["added_cond_kwargs"]["time_ids"] = (
        time_ids.to(**target_device_kwargs),
    )
```
Here, `time_ids` is assigned as a tuple. I modified it to:

```python
if time_ids is not None and hasattr(time_ids, "to"):
    batch["added_cond_kwargs"]["time_ids"] = time_ids.to(**target_device_kwargs)
```
The code started running normally, and I successfully trained SDXL.
